{% set name = "jupyterlab-gt-coar-theme" %}
{% set version = "0.2.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d238d6c7e56c2f30211eb405e32d337ecec2abea82bdfe294bceb9a0ff4d21b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jupyterlab >=3,<4
    - python >=3.6

test:
  imports:
    - jupyterlab_gt_coar_theme
  commands:
    - pip check
    - jupyter labextension list
  requires:
    - pip

about:
  home: https://github.com/gt-coar/jupyterlab-gt-coar-theme
  summary: an unofficial Georgia Tech theme for JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
